# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("http://pinplay.me/")
    self.driver.set_window_size(1258, 815)
    self.driver.find_element(By.CSS_SELECTOR, ".ClickHere:nth-child(1)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".ClickHere:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".close").click()
    self.driver.find_element(By.CSS_SELECTOR, "span").click()
    self.driver.find_element(By.ID, "login-username").click()
    self.driver.find_element(By.CSS_SELECTOR, ".spotify-logo").click()
    self.driver.close()
  
