# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLoginandplaylistgenerationNonexplicitDancePhx():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loginandplaylistgenerationNonexplicitDancePhx(self):
    self.driver.get("http://pinplay.me/")
    self.driver.set_window_size(1258, 815)
    self.driver.find_element(By.CSS_SELECTOR, "span").click()
    self.driver.find_element(By.CSS_SELECTOR, "span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ClickHere:nth-child(1)").click()
    self.driver.find_element(By.NAME, "city").click()
    dropdown = self.driver.find_element(By.NAME, "city")
    dropdown.find_element(By.XPATH, "//option[. = 'PHX']").click()
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3) > input").click()
    self.driver.find_element(By.NAME, "genre").click()
    dropdown = self.driver.find_element(By.NAME, "genre")
    dropdown.find_element(By.XPATH, "//option[. = 'dance']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".submit").click()
    self.driver.close()
  
